sudo: false
language: python
jobs:
  include:
    - python: 3.6.9
      script: make test_skip_metaculus
    - python: 3.7.9
      script: make test
    - python: 3.8.5
      script: make test_skip_metaculus
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - make lint
  - make docs
after_success:
  - poetry run codecov
